### ISSUE TITLE
"--" (double hyphen) in a tag breaks the addon and the Browser

### ISSUE THREAD

**Issue by aleksejrs** [pneff/anki-hierarchical-tags#3]
```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/main.py", line 649, in keyPressEvent
    self.onBrowse()
  File "/usr/share/anki/aqt/main.py", line 712, in onBrowse
    aqt.dialogs.open("Browser", self)
  File "/usr/share/anki/aqt/__init__.py", line 61, in open
    instance = creator(*args)
  File "/usr/share/anki/aqt/browser.py", line 364, in __init__
    self.setupTree()
  File "/usr/share/anki/aqt/browser.py", line 740, in setupTree
    self.buildTree()
  File "/usr/share/anki/aqt/browser.py", line 755, in buildTree
    self._userTagTree(root)
  File "/usr/share/anki/anki/hooks.py", line 61, in repl
    return new(_old=old, *args, **kwargs)
  File "/home/fca/Anki/addons/hierarchical_tags_addon/hierarchical_tags.py", line 40, in _userTagTree
    components = map(unifyComponentCase, components)
  File "/home/fca/Anki/addons/hierarchical_tags_addon/hierarchical_tags.py", line 24, in unifyComponentCase
    return c[0].lower() + c[1:]
IndexError: string index out of range
```

**Comment by aleksejrs** [comment]
It happened only with the case unification patch.  It even crashed with 1-character segments.  Sorry about this.  Fixed in https://github.com/pneff/anki-hierarchical-tags/pull/2/commits/81b33797351573158ea5b60285281f14fd6ca836
